/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartidasIndexRouteImport } from './routes/partidas.index'
import { Route as QuadrasIndexRouteImport } from './routes/quadras.index'
import { Route as QuadrasCourtIdRouteImport } from './routes/quadras.$courtId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidasIndexRoute = PartidasIndexRouteImport.update({
  id: '/partidas/',
  path: '/partidas/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuadrasIndexRoute = QuadrasIndexRouteImport.update({
  id: '/quadras/',
  path: '/quadras/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuadrasCourtIdRoute = QuadrasCourtIdRouteImport.update({
  id: '/quadras/$courtId',
  path: '/quadras/$courtId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quadras/$courtId': typeof QuadrasCourtIdRoute
  '/partidas/': typeof PartidasIndexRoute
  '/quadras/': typeof QuadrasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quadras/$courtId': typeof QuadrasCourtIdRoute
  '/partidas': typeof PartidasIndexRoute
  '/quadras': typeof QuadrasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quadras/$courtId': typeof QuadrasCourtIdRoute
  '/partidas/': typeof PartidasIndexRoute
  '/quadras/': typeof QuadrasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quadras/$courtId' | '/partidas/' | '/quadras/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quadras/$courtId' | '/partidas' | '/quadras'
  id: '__root__' | '/' | '/quadras/$courtId' | '/partidas/' | '/quadras/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuadrasCourtIdRoute: typeof QuadrasCourtIdRoute
  PartidasIndexRoute: typeof PartidasIndexRoute
  QuadrasIndexRoute: typeof QuadrasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partidas/': {
      id: '/partidas/'
      path: '/partidas'
      fullPath: '/partidas/'
      preLoaderRoute: typeof PartidasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quadras/': {
      id: '/quadras/'
      path: '/quadras'
      fullPath: '/quadras/'
      preLoaderRoute: typeof QuadrasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quadras/$courtId': {
      id: '/quadras/$courtId'
      path: '/quadras/$courtId'
      fullPath: '/quadras/$courtId'
      preLoaderRoute: typeof QuadrasCourtIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuadrasCourtIdRoute: QuadrasCourtIdRoute,
  PartidasIndexRoute: PartidasIndexRoute,
  QuadrasIndexRoute: QuadrasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
